<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE cd_carta [
        <!ELEMENT cd_carta (cd)*>
        <!ELEMENT cd (titulo, artista, pais, discografica, precio, Año)*>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT artista (#PCDATA)>
        <!ELEMENT pais (#PCDATA)>
        <!ELEMENT discografica (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ELEMENT Año (#PCDATA)>
        ]>

<cd_carta>
    <cd>
        <titulo>Still got the blues</titulo>
        <artista>Gary Moore</artista>
        <pais>UK</pais>
        <discografica>Virgin Records</discografica>
        <precio>10.20</precio>
        <Año>1990</Año>
    </cd>
    <cd>
        <titulo>One night only</titulo>
        <artista>Bee Gees</artista>
        <pais>UK</pais>
        <discografica>Polydor</discografica>
        <precio>10.90</precio>
        <Año>1998</Año>
    </cd>
    <cd>
        <titulo>When a man loves a woman</titulo>
        <artista>Percy Sledge</artista>
        <pais>USA</pais>
        <discografica>Atlantic</discografica>
        <precio>8.70</precio>
        <Año>1987</Año>
    </cd>
    <cd>
        <titulo>Big Willie style</titulo>
        <artista>Will Smith</artista>
        <pais>USA</pais>
        <discografica>Columbia</discografica>
        <precio>9.90</precio>
        <Año>1997</Año>
    </cd>
    <cd>
        <titulo>La cancion de Juan Perro</titulo>
        <artista>Radio Futura</artista>
        <pais>España</pais>
        <discografica>Sony Music-Ariola</discografica>
        <precio>9.90</precio>
        <Año>1987</Año>
    </cd>
    <cd>
        <titulo>The dock of the bay</titulo>
        <artista>Otis Redding</artista>
        <pais>USA</pais>
        <discografica>Atlantic</discografica>
        <precio>7.90</precio>
        <Año>1987</Año>
    </cd>
</cd_carta>