<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE Mensajes [
        <!ELEMENT Mensajes (Mensaje)*>
        <!ELEMENT Mensaje (Remitente, Destinatario, Asunto, Texto)*>
        <!ELEMENT Remitente (nombre|email)*>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT Destinatario (nombre|email)*>
        <!ELEMENT Asunto (#PCDATA)>
        <!ELEMENT Texto (parrafo)*>
        <!ELEMENT parrafo (#PCDATA)>
        ]>

<Mensajes>
    <Mensaje>
        <Remitente>
            <nombre>Alfredo Reino</nombre>
            <email>alf@ibium.com</email>
        </Remitente>
        <Destinatario>
            <nombre>Bill Clinton</nombre>
            <email>president@whitehouse.gov</email>
        </Destinatario>
        <Asunto>Hola Bill</Asunto>
        <Texto>
            <parrafo>¿Hola qué tal?</parrafo>
            <parrafo>Hace mucho tiempo que no escribes. A ver si llamas y quedamos pronto.</parrafo>
            <parrafo>Un saludo.</parrafo>
        </Texto>
    </Mensaje>
</Mensajes>